### ISSUE TITLE
Random mode always starts with first song

### ISSUE THREAD

**Issue by TomCat666** [koobo/HippoPlayer#7] opened 2021-11-03 06:08 UTC
If you have set the Play to "Modules in random order" and you start the Hippo Player it always loads and plays the first song in the list at the beginning. It would be nice if even the first song would be randomized.

**Comment by koobo** [comment] 2021-11-03 07:39
Can you provide an exact sequence to reproduce this? 
A similar kind of a bug was in v2.47 but it was fixed in v2.48.

**Comment by TomCat666** [comment] 2021-11-03 08:19
Sure...
http://pc.sux.org/tomcat/HippoRandom.mkv

Here is the video of it.
I start Hippo Player, press the PLAY button, select ALL modules and press OK. It will play the first module even if the random mode is turned on.

**Comment by koobo** [comment] 2021-11-03 10:04
Yeah, this seems to be a bug, or a feature, I'm leaning towards a bug :-) It's also an old one.

**Comment by koobo** [comment] 2021-11-29 14:11
Should be ok in v2.49.

**Comment by TomCat666** [comment] 2021-11-29 14:33
Thank you. Works !

**Closed as completed** 2021-12-08 17:17 UTC
