### ISSUE TITLE
incorrect operation of the file requester

### ISSUE THREAD

**Issue by evgenius123** [koobo/HippoPlayer#10] opened 2022-02-10 03:34 UTC
when you double-click on a module in the built-in file requester, it starts playing not the clicked one, but the previous one. the selected one is highlighted in the list. sometimes it starts to play something junk

**Comment by koobo** [comment] 2022-02-17 05:36
Some questions!
Could you describe the exact steps to reproduce this? Also, does this happen always? Is this a new bug, that is, did it work in the v2.45 release for example? Do you have some patches running that modify the window visuals, such as the title bar height?

**Comment by evgenius123** [comment] 2022-06-19 12:12
I use Workbench 40.42, Kickstart 40.68, in multicolor mode (usually 32). no one program modify heights of titlebars.
1) I open Hippoplayer 2.50
2) I go to directory tree tab
3) I go to Media:MOD/ drawer (314 files, take 0.8 sec to open)
4) I open, for exmple, sixth file in list. It select sixth file, but move list up a little and highlited next module in list.
5) Now, if I select some file, program highlighted selected module, but starts playing previous one.
6) I can't play last module in list because of this issue.

**Comment by koobo** [comment] 2022-06-19 16:00
Hi,
I tried to reproduce this but failed. Here's what I did:

1. Open Hippo v2.52
2. Select file browser mode 
3. Open folder with about 400 files
4. Select  any module and play. Selected module plays correctly.
5. Try to also play the last module. Also works.

I used three different ways to browse: pressing the enter key, double clicking with mouse, selecting item with mouse and then pressing the "Play" button. 

Can you think of anything else that could be useful information?
Does the problem only appear in filebrowser, not in the normal list view or favorites view?

**Comment by evgenius123** [comment] 2022-06-26 23:29
I never noticed this problem in playlist mode, and in "favorites" mode I just don't have so many modules)
I notice this strange problem only in directory mode.
What can I do to help to localize source of problem? Was some logs can be useful? From, idk, DOSTrace, for example?

**Comment by koobo** [comment] 2022-06-27 03:58
Could you try to launch hip "without startup sequence" and see if the problem happens?  This is to see if there are any other applications or patches that might affect.

Also it would be interesting to see a video about it, if possible.

**Comment by koobo** [comment] 2022-06-27 04:21
I just noticed that if "Big buttons" is enabled it's not possible to double click on the last items in the list. Do you have "Big buttons" enabled?

**Comment by evgenius123** [comment] 2022-06-27 08:22
Where to find answer? never see this option.
I can send you all folder of my mods, maybe this bug depends on specific modules?
It appear from 5-th module on list, when first line, with folder name, scroll off, if "filebox" setting is "8"

**Comment by evgenius123** [comment] 2022-06-27 08:34
https://youtu.be/rtpnvx4wWzI
here's link to video where bug is appear. not have my voice as sound, just
short parts of modules and mouse clicking.

пн, 27 июн. 2022 г. в 07:22, Kari-Pekka Koljonen ***@***.***>:

**Comment by koobo** [comment] 2022-06-27 09:00
Thank you for the video! I will see if I can make something out of it.
"Big buttons" is an option in prefs, and according to the video you don't have it enabled, sorry about being unclear.

**Comment by koobo** [comment] 2022-06-27 09:51
I'm guessing you have "play modules in random order" enabled in Prefs? I think the problem is related to that. In this mode each time a new module double clicked there will be an extra refresh to erase the random play markers in the list. There's a bug here that makes the list center, which it should not do actually.

**Comment by evgenius123** [comment] 2022-06-28 11:39
Yep, Goal! Bug disappear when I change "modules in random order" to "list repeatedly".

**Comment by koobo** [comment] 2022-06-29 13:53
Could you try out this test version and see if the bug is fixed for you: https://github.com/koobo/HippoPlayer/blob/dev/dist/hip-test

**Comment by evgenius123** [comment] 2022-07-02 07:08
Yep, no issue in this build. Player do their work correctly, with "random order" file requester don't mess up with modules, and also plays it randomly. Thanks!

**Comment by koobo** [comment] 2022-07-02 07:13
Ok, thanks for confirming 👍  I will include this fix in the next release.

**Comment by koobo** [comment] 2022-07-14 05:41
Fixed in v2.53.

**Closed as completed by koobo** 2022-07-14 05:41 UTC
